import { getDb } from '../db/database.js';
import { generateCreativeSummary } from './openaiService.js';

const DEFAULT_PROMPT =
  'Without ad-hoc reasoning and rigorous thinking anaylze these ads numbers and provide rigorous insights';

const DEFAULT_SETTINGS = {
  prompt: DEFAULT_PROMPT,
  mode: 'analyze',
  verbosity: 'low',
  autoEnabled: true
};

const CREATIVE_SUMMARY_STORES = ['vironax', 'shawq'];

const getDateStringInTimezone = (date, timeZone) => {
  const locale = date.toLocaleString('en-US', { timeZone });
  const tzDate = new Date(locale);
  return tzDate.toISOString().split('T')[0];
};

const getNowInTimezone = (timeZone) => {
  const locale = new Date().toLocaleString('en-US', { timeZone });
  return new Date(locale);
};

const buildCreativeSummaryQuestion = (prompt, mode, verbosity) => {
  const modeInstruction = mode === 'summarize'
    ? 'Show what changed and organize data in a readable meaningful way, to be comprehended at a glance.'
    : 'interpret the funnel numbers → diagnose what changed + why → give prioritized actions/tests.';
  const verbosityLabel = verbosity === 'medium' ? 'Medium' : 'Low';
  return `${prompt}\n\nMode: ${modeInstruction}\nVerbosity: ${verbosityLabel}`;
};

const getWeekRange = (timeZone) => {
  const now = getNowInTimezone(timeZone);
  const day = now.getDay();
  const end = new Date(now);
  end.setHours(0, 0, 0, 0);
  const daysFromMonday = day === 0 ? 6 : day - 1;
  const start = new Date(end);
  start.setDate(end.getDate() - daysFromMonday);
  return {
    startDate: getDateStringInTimezone(start, timeZone),
    endDate: getDateStringInTimezone(end, timeZone)
  };
};

const getDayRange = (timeZone, offsetDays = 0) => {
  const now = getNowInTimezone(timeZone);
  const target = new Date(now);
  target.setDate(target.getDate() + offsetDays);
  const date = getDateStringInTimezone(target, timeZone);
  return { startDate: date, endDate: date };
};

export const getCreativeSummarySettings = (store) => {
  const db = getDb();
  const row = db.prepare(`
    SELECT prompt, mode, verbosity, auto_enabled as autoEnabled
    FROM creative_summary_settings
    WHERE store = ?
  `).get(store);

  if (!row) {
    return { ...DEFAULT_SETTINGS };
  }

  return {
    prompt: row.prompt || DEFAULT_SETTINGS.prompt,
    mode: row.mode || DEFAULT_SETTINGS.mode,
    verbosity: row.verbosity || DEFAULT_SETTINGS.verbosity,
    autoEnabled: row.autoEnabled !== 0
  };
};

export const updateCreativeSummarySettings = (store, updates = {}) => {
  const db = getDb();
  const current = getCreativeSummarySettings(store);
  const next = {
    prompt: updates.prompt ?? current.prompt,
    mode: updates.mode ?? current.mode,
    verbosity: updates.verbosity ?? current.verbosity,
    autoEnabled: updates.autoEnabled ?? current.autoEnabled
  };

  db.prepare(`
    INSERT INTO creative_summary_settings (store, prompt, mode, verbosity, auto_enabled, updated_at)
    VALUES (@store, @prompt, @mode, @verbosity, @autoEnabled, datetime('now'))
    ON CONFLICT(store) DO UPDATE SET
      prompt = excluded.prompt,
      mode = excluded.mode,
      verbosity = excluded.verbosity,
      auto_enabled = excluded.auto_enabled,
      updated_at = datetime('now')
  `).run({
    store,
    prompt: next.prompt,
    mode: next.mode,
    verbosity: next.verbosity,
    autoEnabled: next.autoEnabled ? 1 : 0
  });

  return next;
};

export const getLatestCreativeSummary = (store) => {
  const db = getDb();
  return db.prepare(`
    SELECT *
    FROM creative_funnel_summaries
    WHERE store = ? AND dismissed_at IS NULL
    ORDER BY generated_at DESC
    LIMIT 1
  `).get(store);
};

export const saveCreativeSummary = ({
  store,
  summaryType,
  prompt,
  verbosity,
  content,
  startDate,
  endDate,
  generatedAt = new Date().toISOString(),
  autoGenerated = false
}) => {
  const db = getDb();
  const result = db.prepare(`
    INSERT INTO creative_funnel_summaries (
      store, summary_type, prompt, verbosity, content,
      start_date, end_date, generated_at, auto_generated
    ) VALUES (
      @store, @summaryType, @prompt, @verbosity, @content,
      @startDate, @endDate, @generatedAt, @autoGenerated
    )
  `).run({
    store,
    summaryType,
    prompt,
    verbosity,
    content,
    startDate,
    endDate,
    generatedAt,
    autoGenerated: autoGenerated ? 1 : 0
  });

  return result.lastInsertRowid;
};

export const dismissCreativeSummary = (store, summaryId) => {
  const db = getDb();
  return db.prepare(`
    UPDATE creative_funnel_summaries
    SET dismissed_at = datetime('now')
    WHERE id = ? AND store = ?
  `).run(summaryId, store);
};

const hasSummaryForRange = (store, summaryType, startDate, endDate) => {
  const db = getDb();
  const existing = db.prepare(`
    SELECT id
    FROM creative_funnel_summaries
    WHERE store = ? AND summary_type = ? AND start_date = ? AND end_date = ?
    ORDER BY generated_at DESC
    LIMIT 1
  `).get(store, summaryType, startDate, endDate);
  return Boolean(existing);
};

export const generateCreativeSummaryForRange = async ({
  store,
  summaryType,
  prompt,
  verbosity,
  startDate,
  endDate,
  autoGenerated
}) => {
  const question = buildCreativeSummaryQuestion(prompt, summaryType, verbosity);
  const result = await generateCreativeSummary({
    question,
    store,
    mode: summaryType,
    verbosity,
    reasoningEffort: 'medium',
    startDate,
    endDate
  });

  const summaryId = saveCreativeSummary({
    store,
    summaryType,
    prompt,
    verbosity,
    content: result.text || '',
    startDate,
    endDate,
    autoGenerated
  });

  return { summaryId, ...result };
};

export const runCreativeSummaryAutoGeneration = async ({ type, timeZone = 'Europe/Istanbul' }) => {
  const tasks = CREATIVE_SUMMARY_STORES.map(async (store) => {
    const settings = getCreativeSummarySettings(store);
    if (!settings.autoEnabled) return null;

    const range = type === 'weekly'
      ? getWeekRange(timeZone)
      : getDayRange(timeZone, 0);

    if (hasSummaryForRange(store, settings.mode, range.startDate, range.endDate)) {
      return null;
    }

    return await generateCreativeSummaryForRange({
      store,
      summaryType: settings.mode,
      prompt: settings.prompt,
      verbosity: settings.verbosity,
      startDate: range.startDate,
      endDate: range.endDate,
      autoGenerated: true
    });
  });

  return Promise.all(tasks);
};

export const maybeTriggerCreativeSummaryBySpendReset = async (store, timeZone = 'Europe/Istanbul') => {
  const db = getDb();
  const settings = getCreativeSummarySettings(store);
  if (!settings.autoEnabled) return null;

  const now = getNowInTimezone(timeZone);
  const today = getDateStringInTimezone(now, timeZone);
  const yesterday = getDateStringInTimezone(new Date(now.getTime() - 24 * 60 * 60 * 1000), timeZone);

  const todaySpend = db.prepare(`
    SELECT SUM(spend) as total
    FROM meta_daily_metrics
    WHERE store = ? AND date = ?
  `).get(store, today)?.total || 0;

  const yesterdaySpend = db.prepare(`
    SELECT SUM(spend) as total
    FROM meta_daily_metrics
    WHERE store = ? AND date = ?
  `).get(store, yesterday)?.total || 0;

  const hour = now.getHours();
  if (todaySpend > 0 || yesterdaySpend <= 0 || hour > 6) {
    return null;
  }

  if (hasSummaryForRange(store, settings.mode, yesterday, yesterday)) {
    return null;
  }

  return await generateCreativeSummaryForRange({
    store,
    summaryType: settings.mode,
    prompt: settings.prompt,
    verbosity: settings.verbosity,
    startDate: yesterday,
    endDate: yesterday,
    autoGenerated: true
  });
};

export const getCreativeSummaryQuestion = buildCreativeSummaryQuestion;
